/**
 * build-openers-sql.ts — turn the verified 2026-27 capture into ONE date per
 * state per species, and emit the load as a migration.
 *
 *   npx tsx scripts/seasons/build-openers-sql.ts            # write + report
 *   npx tsx scripts/seasons/build-openers-sql.ts --report   # report only
 *
 * Writes nothing to the database. It emits SQL; the main session applies it.
 *
 * The selection rule lives in `src/lib/seasonOpeners.ts` and is unit-tested
 * there — this file is I/O, formatting and receipts only. Deliberately absent
 * from the emitted rows: bag limits, closing dates, splits, zone structures.
 * Those are the state's to publish and ours to link to (Amendment 1.5 ruling 2).
 */

import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import { deriveOpeners, type CaptureRecord } from "../../src/lib/seasonOpeners";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..");
const CAPTURE = path.join(ROOT, "data", "seasons", "2026-27.json");
const OUT = path.join(ROOT, "supabase", "migrations", "20260726020000_load_2026_27_openers.sql");

const reportOnly = process.argv.includes("--report");

function lit(s: string | null | undefined): string {
  if (s == null) return "NULL";
  return `'${s.replace(/'/g, "''")}'`;
}

const records = JSON.parse(fs.readFileSync(CAPTURE, "utf-8")) as CaptureRecord[];
const { openers, absences, warnings } = deriveOpeners(records);

const seasonYear = records[0]?.season_year ?? "2026-2027";

/* ── the VALUES rows: openers first, then absences, both state-ordered ── */

type Row = {
  species: string;
  state: string;
  zone: string;
  opensOn: string | null;
  status: string;
  provisional: string; // 'true' | 'false' | NULL for absences we hold no label for
  provisionalNote: string | null;
  notes: string | null;
  sourceUrl: string | null;
  fetchedAt: string;
  confidence: string;
  recheckAfter: string | null;
  sourceRecords: number;
};

const rows: Row[] = [
  ...openers.map<Row>((o) => ({
    species: o.species,
    state: o.stateAbbr,
    zone: o.zone,
    opensOn: o.opensOn,
    status: "ok",
    provisional: o.provisional ? "true" : "false",
    provisionalNote: o.provisional ? o.provisionalNote : null,
    // No notes on an opener row. The capture's notes carry bag-limit and split
    // detail, which is exactly the content this scope refuses to republish.
    notes: null,
    sourceUrl: o.sourceUrl,
    fetchedAt: o.fetchedAt,
    confidence: o.confidence,
    recheckAfter: null,
    sourceRecords: o.sourceRecords,
  })),
  ...absences.map<Row>((a) => ({
    species: a.species,
    state: a.stateAbbr,
    zone: "Statewide",
    opensOn: null,
    status: a.status,
    provisional: "NULL",
    provisionalNote: null,
    // The absence's whole value is the state's own reason, verbatim and whole.
    notes: a.reason,
    sourceUrl: a.sourceUrl,
    fetchedAt: a.fetchedAt,
    confidence: "high",
    recheckAfter: a.recheckAfter,
    sourceRecords: a.sourceRecords,
  })),
].sort((a, b) => a.state.localeCompare(b.state) || a.species.localeCompare(b.species));

const values = rows
  .map(
    (r) =>
      `  (${lit(r.species)}, ${lit(r.state)}, ${lit(r.zone)}, ${r.opensOn ? lit(r.opensOn) : "NULL"}, ` +
      `${lit(r.status)}, ${r.provisional === "NULL" ? "NULL" : lit(r.provisional)}, ${lit(r.provisionalNote)}, ` +
      `${lit(r.notes)}, ${lit(r.sourceUrl)}, ${lit(r.fetchedAt)}, ${lit(r.confidence)}, ` +
      `${r.recheckAfter ? lit(r.recheckAfter) : "NULL"}, '${r.sourceRecords}')`,
  )
  .join(",\n");

const nOpeners = rows.filter((r) => r.status === "ok").length;
const nAbsences = rows.length - nOpeners;

const sql = `-- 2026-27 WATERFOWL OPENERS — one date per state per species.
--
-- Amendment 1.5 ruling 2: openers only, link out for everything else. The
-- countdown needs one number; zones, splits, closing dates and bag limits are
-- the state's to publish and ours to point at. Being wrong on a bag limit is a
-- citation for the hunter, and \`hunt_regulation_links\` already holds 243
-- official URLs — so this load carries a date and a link, and nothing else.
--
-- Generated by scripts/seasons/build-openers-sql.ts from data/seasons/2026-27.json
-- (${records.length} verified capture records). DO NOT HAND-EDIT: re-run the script.
--
-- Selection rule: earliest \`open\` across the pair's status='ok' records. Early
-- and special seasons (September resident goose, September teal, the August
-- goose take) win when they are earliest, and the zone label names them so the
-- card can say which season the date belongs to. Rows whose status is
-- not_published / no_season / closed / conflicted produce NO date — they land
-- with empty dates and the state's own reason in \`notes\`.
--
-- ${nOpeners} openers, ${nAbsences} honest absences, ${rows.length} rows total.
-- Idempotent: zone_slug is the constant 'opener', so re-running updates in place.
-- Requires 20260726010000_hunt_seasons_opener_columns.sql.

WITH capture (
  species_id, state_abbr, zone, opens_on, status, provisional, provisional_note,
  notes, source_url, fetched_at, confidence, recheck_after, source_records
) AS (
  VALUES
${values}
)
INSERT INTO hunt_seasons (
  species_id, state_abbr, state_name, season_type, zone, zone_slug,
  dates, bag_limit, notes, verified, source_url, season_year,
  status, provisional, provisional_note, fetched_at, confidence, recheck_after,
  source_records
)
SELECT
  c.species_id,
  c.state_abbr,
  s.name,
  'opener',
  c.zone,
  'opener',
  CASE
    WHEN c.opens_on IS NULL THEN '[]'::jsonb
    ELSE jsonb_build_array(jsonb_build_object('open', c.opens_on))
  END,
  NULL,                                   -- bag_limit: not ours to publish
  c.notes,
  false,                                  -- verified: no second independent read of THIS row
  -- The page actually read wins; the standing official link is the fallback.
  COALESCE(c.source_url, l.url),
  ${lit(seasonYear)},
  c.status,
  c.provisional::boolean,
  c.provisional_note,
  c.fetched_at::timestamptz,
  c.confidence,
  c.recheck_after::date,
  c.source_records::int
FROM capture c
JOIN hunt_states s ON s.abbreviation = c.state_abbr
LEFT JOIN hunt_regulation_links l
  ON l.species_id = c.species_id AND l.state_abbr = c.state_abbr
ON CONFLICT (species_id, state_abbr, season_type, zone_slug, season_year) DO UPDATE SET
  state_name       = EXCLUDED.state_name,
  zone             = EXCLUDED.zone,
  dates            = EXCLUDED.dates,
  bag_limit        = EXCLUDED.bag_limit,
  notes            = EXCLUDED.notes,
  source_url       = EXCLUDED.source_url,
  status           = EXCLUDED.status,
  provisional      = EXCLUDED.provisional,
  provisional_note = EXCLUDED.provisional_note,
  fetched_at       = EXCLUDED.fetched_at,
  confidence       = EXCLUDED.confidence,
  recheck_after    = EXCLUDED.recheck_after,
  source_records   = EXCLUDED.source_records;

-- Receipts. A load that cannot count itself is a belief (Amendment 1.5 §6).
DO $verify$
DECLARE
  n_total int;
  n_dated int;
  n_absent int;
  n_nolink int;
BEGIN
  SELECT
    count(*),
    count(*) FILTER (WHERE jsonb_array_length(dates) = 1),
    count(*) FILTER (WHERE jsonb_array_length(dates) = 0),
    count(*) FILTER (WHERE source_url IS NULL)
  INTO n_total, n_dated, n_absent, n_nolink
  FROM hunt_seasons
  WHERE season_year = ${lit(seasonYear)} AND season_type = 'opener';

  IF n_total <> ${rows.length} OR n_dated <> ${nOpeners} OR n_absent <> ${nAbsences} THEN
    RAISE EXCEPTION 'opener load mismatch: % rows / % dated / % absent (expected ${rows.length} / ${nOpeners} / ${nAbsences})',
      n_total, n_dated, n_absent;
  END IF;

  RAISE NOTICE '2026-27 openers loaded: % rows, % dated, % honest absences, % without any link',
    n_total, n_dated, n_absent, n_nolink;
END
$verify$;
`;

/* ─────────────────────────────── report ─────────────────────────────── */

const byStatus = new Map<string, string[]>();
for (const a of absences) {
  const k = a.status;
  byStatus.set(k, [...(byStatus.get(k) ?? []), `${a.stateAbbr} ${a.species}`]);
}

console.log(`capture:   ${records.length} records → ${openers.length + absences.length} state-species pairs`);
console.log(`openers:   ${openers.length} (a real countdown)`);
console.log(`absences:  ${absences.length} (no date, the state's own reason)`);
for (const [k, v] of [...byStatus].sort()) console.log(`             ${k}: ${v.join(", ")}`);
console.log(`provisional openers: ${openers.filter((o) => o.provisional).length}`);
console.log(`openers whose winning record is not high-confidence: ${openers.filter((o) => o.confidence !== "high").length}`);
console.log(`openers collapsed from more than one published season row: ${openers.filter((o) => o.sourceRecords > 1).length}`);
console.log(`openers sharing their date with another zone: ${openers.filter((o) => o.sameDayOpeners > 0).length}`);
console.log(`openers missing a captured source_url: ${openers.filter((o) => !o.sourceUrl).length}`);
if (warnings.length) {
  console.log(`\nwarnings (${warnings.length}) — contradictions in the capture, reported not smoothed:`);
  for (const w of warnings) console.log(`  ! ${w}`);
}

const earliest = [...openers].sort((a, b) => a.opensOn.localeCompare(b.opensOn));
console.log(`\nearliest 5: ${earliest.slice(0, 5).map((o) => `${o.stateAbbr} ${o.species} ${o.opensOn}`).join(" · ")}`);
console.log(`latest 5:   ${earliest.slice(-5).map((o) => `${o.stateAbbr} ${o.species} ${o.opensOn}`).join(" · ")}`);

if (!reportOnly) {
  fs.writeFileSync(OUT, sql, "utf-8");
  console.log(`\nwrote ${path.relative(ROOT, OUT)} (${sql.split("\n").length} lines) — NOT applied`);
}
